config/routes.rb
OfficeClerk::Engine.routes.append do
  resources :orders do
    member do
      get :rakennus
    end
  end
  resources :resellers do
    collection do
      get "search" => "resellers#index"
    end
  end
end

Rails.application.routes.draw do

  resources :translations ,  :constraints => { :id => /.*/ } do
    get "missing" , :on => :member
    get "file" , :on => :member
    post "search" , :on => :member
  end

  get '/:page.html',
        :to => 'page#index',
        :defaults => { :page => "index" }

  root :to =>  "page#index" , :defaults => { :page => "index" }

  mount OfficeClerk::Engine => "/"

  match '*path', via: :all, to: 'page#error_404' #if Rails.production?

end

app/models/reseller.rb
class Reseller < ActiveRecord::Base
  validates :name, :presence => true
  validates :post_code, :presence => true

  default_scope {order(post_code: :asc)}
end

app/controllers/resellers_controller.rb
class ResellersController < AdminController
  before_action :set_reseller, only: [:show, :edit, :update, :destroy]

  # GET /resellers
  def index
    @q = Reseller.search params[:q]
    @reseller_scope = @q.result(:distinct => true)
    @resellers = @reseller_scope.paginate( :page => params[:page],:per_page => 20)
  end

  # GET /resellers/1
  def show
  end

  # GET /resellers/new
  def new
    @reseller = Reseller.new
  end

  # GET /resellers/1/edit
  def edit
  end

  # POST /resellers
  def create
    @reseller = Reseller.new(reseller_params)

    if @reseller.save
      redirect_to resellers_url, notice: 'Reseller was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /resellers/1
  def update
    if @reseller.update(reseller_params)
      redirect_to resellers_url, notice: 'Reseller was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /resellers/1
  def destroy
    @reseller.destroy
    redirect_to resellers_url, notice: 'Reseller was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reseller
      @reseller = Reseller.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def reseller_params
      params.require(:reseller).permit(:name, :address, :city, :link , :post_code)
    end
end

app/helpers/resellers_helper.rb
module ResellersHelper
end

app/views/resellers/_form.html.haml
= bootstrap_form_for(@reseller) do |f|
  - if @reseller.errors.any?
    #error_explanation
      %h2
        = pluralize(@reseller.errors.count, "error")
        prohibited this reseller from being saved:
      %ul
        - @reseller.errors.full_messages.each do |message|
          %li= message
  .field
    = f.text_field :name
  .field
    = f.text_area :address, :rows => 2
  .field
    = f.text_field :post_code
  .field
    = f.text_field :city
  .field
    = f.text_field :link
  .actions
    = f.submit

app/views/resellers/edit.html.haml
%h1 Muokkaa jälleenmyyjän tietoja
= render 'form'
= link_to 'Show', @reseller
|
= link_to 'Back', resellers_path

%br
%br
		
= link_to t(:destroy) , reseller_path(@reseller), :data => { :confirm => t(:are_you_sure) }, :method => :delete, :title => t(:destroy) , :class => "btn btn-danger"

app/views/resellers/index.html.haml
.row
  .col-md-9.resellers
    .row
      .col-md-10
        %h2= t(:resellers)
        = paginate @resellers
      .col-md-2
        = link_to  t(:new) + ' ' + t(:reseller) , new_reseller_path , :class => "btn btn-primary"
  .col-md-3
    = image_tag "resellers.jpg" , :class => "img-responsive"
.row
  .col-md-9
    %div
      %table.table.table-striped.table-bordered.table-condensed
        %thead
          %tr
            %th=sort_link  @q, :name
            %th=t(:address)
            %th=t(:post_code)
            %th=t(:city)
            %th{:colspan => "2"}
              %label.checkbox
                = @reseller_scope.length.to_s + " " + t(:resellers).to_s
        %tbody
          - @resellers.each do |reseller|
            %tr{:class => "line-#{cycle("1","2")}"}
              %td=reseller.name
              %td=reseller.address
              %td=reseller.post_code
              %td=reseller.city
              %td= link_to t(:show) , reseller_path(reseller), :title => t(:show)
              %td= link_to t(:edit), edit_reseller_path(reseller), :title => t(:edit)
    = paginate @resellers
  .col-md-3
    = search_form_for @q, :html => { :class => "form-horizontal" }, :method => :get do |f|
      .form-group
        = f.text_field :name_cont , :class => "form-control" , :placeholder =>  t(:name)
      .form-group
        = f.text_field :address_cont ,:class => "form-control" , :placeholder =>  t(:address)
      = f.submit t(:filter),  :id => :filter , :class => "btn btn-success"
      = link_to  t(:cancel), resellers_path, :class => "btn btn-warning"

app/views/resellers/new.html.haml
%h1 Uusi Jälleenmyyjä
= render 'form'

app/views/resellers/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @reseller.name
%p
  %strong Address:
  = @reseller.address
%p
  %strong Postcode:
  = @reseller.post_code
%p
  %strong City:
  = @reseller.city
%p
  %strong Link:
  = @reseller.link
= link_to 'Muoka', edit_reseller_path(@reseller)
|
= link_to 'Listalle', resellers_path